### ISSUE TITLE
Languages by user

### ISSUE THREAD

**Issue by aknsal** [opencodeiiita/Geek-Editor-Backend#115]
Create an API to get all the languages used by a user and add that route in Readme as well.

**Comment by raghavgoel25** [comment]
claim

**Comment by diyawaghmare** [comment]
claim

**Comment by aknsal** [comment]
@raghavgoel25 you already have 3 issues assigned to you.

**Comment by VineethKumarM** [comment]
If the issue is still open I want to work on this.

**Comment by raghavgoel25** [comment]
claim
