### ISSUE TITLE
Change user routes

### ISSUE THREAD

**Issue by aknsal** [opencodeiiita/Geek-Editor-Backend#132]
Update the user routes so that every route related to user should start with `/user`. Make a different file for all the user routes.
For eg. the route to update user data the route is `/update/:id`, this can be changed to `/user/update/:id`.

**Comment by ashutosh3027** [comment]
claim

**Comment by VineethKumarM** [comment]
Claim.

**Comment by rahulsingh-20** [comment]
claim
