### ISSUE TITLE
Add an Api to update profile

### ISSUE THREAD

**Issue by aknsal** [opencodeiiita/Geek-Editor-Backend#2]

**Comment by Ksathwik03** [comment]
Can u alloborate and i want to claim it

**Comment by A-Spiral-Forge** [comment]
please elaborate, I want to claim

**Comment by shlesh** [comment]
Claim, I want to work on this issue,

**Comment by aknsal** [comment]
> Can u alloborate and i want to claim it

Create a put request to update the profile of user by getting data from `req.body` and add the data to mongoDB. For beginners majority of the code has already been commented, you just need to edit it so as to make it work.

**Comment by Ksathwik03** [comment]
> > Can u alloborate and i want to claim it
> 
> Create a put request to update the profile of user by getting data from `req.body` and add the data to mongoDB. For beginners majority of the code has already been commented, you just need to edit it so as to make it work.

I want to work on it

**Comment by adtoria** [comment]
Claim

**Comment by jalanprakhar** [comment]
claim

**Comment by rankit2001** [comment]
claim
