### ISSUE TITLE
Add an API to get user info

### ISSUE THREAD

**Issue by aknsal** [opencodeiiita/Geek-Editor-Backend#24]
Add a controller to get user info by passing userId as a parameter. Add a route for this. It should be a get method at `/profile/:id`.

**Comment by kaneki-ken260** [comment]
claim

**Comment by prxtikk-18** [comment]
claim

**Comment by Ksathwik03** [comment]
> @kaneki-ken260 Any Updates?

Since 2 days are completed i would like to take the issue.

**Comment by aknsal** [comment]
If this issue is not solved today by 5pm this would be opened again. @kaneki-ken260

**Comment by Ksathwik03** [comment]
> If this issue is not solved today by 5pm this would be opened again. @kaneki-ken260

5 pm done i want to claim it

**Comment by aknsal** [comment]
As no PR is received this issue is being reassigned.
