### ISSUE TITLE
Add docker

### ISSUE THREAD

**Issue by rcovery** [opencodeiiita/Geek-Editor-Backend#37]
Build docker to improve the development environment.

**Comment by Revathi2306** [comment]
claim

**Comment by prxtikk-18** [comment]
claim

**Comment by VineethKumarM** [comment]
Claim

**Comment by codelord09** [comment]
claim

**Comment by aknsal** [comment]
@rcovery Thank you for your suggestion but as of now we are not planning to implement docker in this project. In future if it is required we will tell you, but right now it is not required.
