### ISSUE TITLE
Email is not validated.

### ISSUE THREAD

**Issue by daniel-aracquine** [opencodeiiita/Geek-Editor-Backend#53]
The email address of a user does not get validated to check whether it's in right format or not. Like i can fill my email as "abc" and it will get accepted. I would like to work on this issue so that only the emails which have a valid format is accepted. For example "abc" won't be accepted but "abc@ad.com" will be accepted as it has the correct format for an email.

**Comment by Monik09** [comment]
claim

**Comment by karankc23** [comment]
claim

**Comment by batflarrow** [comment]
Claim

**Comment by aknsal** [comment]
@daniel-aracquine Thanks for suggestion.  You can start working on it now

**Comment by daniel-aracquine** [comment]
> @daniel-aracquine Thanks for suggestion. You can start working on it now

Great
