### ISSUE TITLE
Setup and add getCode in codecontroller

### ISSUE THREAD

**Issue by aknsal** [opencodeiiita/Geek-Editor-Backend#78]
## Description
Set up `codeController` file and add getCode method (GET Method) at `/:id` which would take `codeId` as param. All routes of code should begin with `/code`. So the route should be get code should be a get method at `/code/:id`.

**Comment by batflarrow** [comment]
> @batflarrow You already have 4 issues assigned.

No no I have only 3 assigned to me currently
