### ISSUE TITLE
Add Followers

### ISSUE THREAD

**Issue by aknsal** [opencodeiiita/Geek-Editor-Backend#85]
## Description
You have to implement a new feature in which users can follow other users.
You can add new fields of Array (Followers and Followings) in user schema and create a new route `/follow/:id`  in api.js which will take the id of a user as a parameter to follow.
Add required methods in the `authController` to add followers and followings to the array.

**Comment by batflarrow** [comment]
Claim

**Comment by daniel-aracquine** [comment]
claim

**Comment by jalanprakhar** [comment]
claim
