### ISSUE TITLE
API to add new code

### ISSUE THREAD

**Issue by aknsal** [opencodeiiita/Geek-Editor-Backend#88]
## Description
Create a new API to add code to code schema and simultaneously add that codeId to code array in userSchema

**Comment by daniel-aracquine** [comment]
claim

**Comment by daniel-aracquine** [comment]
> @daniel-aracquine You already have 4 issues assigned

i have already sent pr for one of them .. does tha count too??

**Comment by Ksathwik03** [comment]
@aknsal since there is no one working on it i would like to work on it

**Comment by rushilpatra** [comment]
> @rushilpatra and @Ksathwik03 You both have 3 issues assigned.

One issue is left to be merged
