### ISSUE TITLE
Improving Authentication

### ISSUE THREAD

**Issue by Ksathwik03** [opencodeiiita/Geek-Editor-Backend#9]
The Authentication of the current project is not checking whether the user is accessing or someone else this can be improved.
I want to work on it.

**Comment by batflarrow** [comment]
claim

**Comment by Ksathwik03** [comment]
@aknsal i am not sure about this but i am thinking in introducing a header based authentication.

**Comment by aknsal** [comment]
For this problem checks can be made if a user is authenticated using passport which would use sessions and cookies and would not be difficult. But we can also implement JWT authentication for this project.
We were thinking to solve this problem at later stage of the project. The issue will be created after reviewing this with the team.

**Comment by Ksathwik03** [comment]
So can i start working on it or the issue is going to be released later

**Comment by aknsal** [comment]
I would say to wait till the issue is created

**Comment by aknsal** [comment]
@Ksathwik03 Are you willing to take this issue now?

**Comment by Ksathwik03** [comment]
Yes

**Comment by aknsal** [comment]
Okay, you have to implement JWT authentication.
