### ISSUE TITLE
Recaptcha verification

### ISSUE THREAD

**Issue by Ksathwik03** [opencodeiiita/Geek-Editor-Backend#93]
To avoid attacks on the server by passing multiple requests captcha verification is required. I would like to implement it @aknsal

**Comment by aknsal** [comment]
Good Idea, but we will implement this idea later when our project is almost ready

**Comment by aknsal** [comment]
@Ksathwik03 do you want to take this issue?

**Comment by raghavgoel25** [comment]
claim

**Comment by varunKT001** [comment]
claim

**Comment by Ksathwik03** [comment]
Claim ✌
